config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#logout"
  resources :users, except: [:new]
  resources :categories, except: [:destroy]

end

app/models/ac_link.rb
# frozen_string_literal: true

class AcLink < ApplicationRecord

    belongs_to :article
    belongs_to :category

end
  

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord

  belongs_to :user

  has_many :ac_links
  has_many :categories, through: :ac_links

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 8 }
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}

    before_save :category_capitalize

    has_many :ac_links
    has_many :articles, through: :ac_links


    def category_capitalize
        self.name = name.capitalize
    end    
end    

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  before_save :email_downcase

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: valid_email_regex }

  def email_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||=  User.find(session[:user_id]) if session[:user_id]
    end    

    def logged_in?
        !!current_user
    end    

    def require_user
        if !logged_in?
            flash[:danger] = "Your are permitted to do this action"
            redirect_to root_path
        end    
    end    
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show destroy update]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.user = User.last
    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit, update or destroy your articles"
      redirect_to root_path
    end 
 end  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 3)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was successfully created"
            redirect_to categories_path
        else
            render 'new'
        end        
    end    

    def edit
        @category = Category.find(params[:id])
    end    

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category successfully edited"
            redirect_to category_path(@category)
        else
           render 'edit'
        end         
    end    

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end    
    
    def require_admin
        if !logged_in? || (logged_in? && !current_user.admin?)
            flash[:danger] = "Only admins can perform this action"
            redirect_to categories_path
        end    
    end    
    
end    

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Invalid Credentials"
            render 'new'
        end        
    end 
    
    def logout
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end    
    
    
end    

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your acccount is successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end    
  end  

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end  

  def destroy
    @user.destroy
    flash[:success] = "User #{@user.username} and all articles created by user have been deleted"
    redirect_to users_path
  end  

  private

  def set_user
    @user = User.find(params[:id])
  end  

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def require_same_user
     if current_user != @user and !current_user.admin?
       flash[:danger] = "You can only edit your profile"
       redirect_to root_path
     end 
  end  

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can delete the user and their articles"
    end  
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end    
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at)%> ago,
              last updated: <%= time_ago_in_words(article.updated_at)%> ago
            </small>
          </div>
        </div>

        <% if article.categories.any? %>
          <p>Categories: <%=  render article.categories %></p>
        <% end %>

        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="row">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-primary btn-md" %>
            <%= link_to "Delete this article", article_path(article),method: :delete, data: {confirm: "Are you sure you want to delete?"},class: "btn btn-danger btn-md" %>
            <%= link_to 'Back to Articles Listing', articles_path, class: "btn btn-success btn-md" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: @article, local: true, class: "form-horizontal" ) do |f|%>
      <div class="form-group">
        <%= f.label :title, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Description of article", autofocus: true%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg" %>
            <%= link_to 'Cancel', articles_path, class: "btn btn-danger btn-lg" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/articles/edit.html.erb
<h2 align="center">Edit existing Article</h2>


<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="center"> Listing all articles</h2>
<div class="center">
  <%= link_to "New Article", new_article_path, style: "color:green; font-size:1.8rem" %>
</div>

<div class="center">
  <%= will_paginate %>
</div>
<%= render 'articles', obj: @articles %>
<div class="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h2 align="center">Create a New Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
  <h2 align=center> Title: <%= @article.title %>  </h2>
  <div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4 center">
            <li>
              Created by
            </li>
            <li>
              <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            </li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li><small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %> </small></li>
          </div>
        </div>
      </ul>
    <% end %>
    <h4 align=center><strong>Description:</strong> </h4>
    <hr>
    <%= simple_format(@article.description) %>

    <% if @article.categories.any? %>
      <p>Categories: <%=  render @article.categories %></p>
    <% end %>

    <% if logged_in? && (current_user == @article.user  || current_user.admin?) %>
      <div class="row">
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary btn-md" %>
        <%= link_to "Delete this article", article_path(@article),method: :delete, data: {confirm: "Are you sure you want to delete?"},class: "btn btn-danger btn-md" %>
        <%= link_to 'Back to Articles Listing', articles_path, class: "btn btn-success btn-md" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge_style" style="background-color: #CEF6F5">
    <%= link_to category.name, category_path(category) %>&nbsp;
</span>    

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: @category, local: true, class: "form-horizontal" ) do |f|%>
      <div class="form-group">
        <%= f.label :name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
          <%= link_to 'Cancel', articles_path, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h2 align="center">Edit category </h2>



<%= render 'shared/errors', obj: @category%>
<%= render 'form', obj: @category%>

app/views/categories/index.html.erb
<h2 align="center">All Categories List</h2>
<div align="center">
  <%= will_paginate %>  
  <% @categories.each do |category|%>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4 center">
          <li class="article-title">
            <%= link_to category.name, category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, 'article') %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h2 align="center">Create new category </h2>



<%= render 'shared/errors', obj: @category%>
<%= render 'form', obj: @category%>

app/views/categories/show.html.erb
<h2 align=center> Category: <%= @category.name %>  </h2>
<% if logged_in? and current_user.admin? %>
  <div class="center">
    <%= link_to "Edit Category", edit_category_path(@category), style: "color:green; font-size:1.8rem" %>
  </div>
<%end %>
<div class="center">
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/articles', obj: @category_articles %>
<div class="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
    <%# <footer class="footer">
        <p class="text-muted">Copyright &copy; <a href="/">Ruby on Rails Course</a></p>
    </footer> %>

app/views/layouts/_messages.html.erb
<%if !flash.empty?%>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <a href=# class="close" data-dismiss="alert">&#215;</a> 
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>  
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id:"logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>

        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path %></li>
              <% Category.all.each do |category|%>
                <li><%= link_to "#{category.name.capitalize}" , category_path(category) %></li>
              <%end%>

              <% if logged_in? && current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "New Category", new_category_path %></li>
              <% end%>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin?%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
              <li><%= link_to 'View your profile', user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%#= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Alpha Blog</h1>
  <%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg btn-xlarge"  %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger fade in collapse" id="panel">
                <div class="panel-heading">
                    <a data-toggle="collapse"   href="#panel"  class="close" >&times </a>
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                </div>
                <div class="panel-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg|%>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<% end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: @user, local: true, class: "form-horizontal" ) do |f|%>
      <div class="form-group">
        <%= f.label :username, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true%>
        </div>
      </div>

      <% if @user.new_record? %>  
        <div class="form-group">
            <%= f.label :password, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true%>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password", autofocus: true%>
            </div>
        </div>
      <% end %>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit (@user.new_record? ? "Sign up" : "Update your account"), class: "btn btn-primary btn-lg" %>
          <%= link_to 'Cancel', articles_path, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h2 align="center">Edit your account</h2>

<%= render 'form'%>

app/views/users/index.html.erb
<h2 align="center">All Alpha Bloggers</h2>
<div align="center">
  <%= will_paginate %>  
  <% @users.all.each do |user|%>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4 center">
          <li>
            <%= link_to gravatar_for(user), user_path(user) %>
          </li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small> <%= pluralize(user.articles.count, "article") if user.articles %> </small></li>
          <% if logged_in? and current_user.admin?%>
            <%= link_to "Delete this user", user_path(user),method: :delete, data: {confirm: "Are you sure you want to delete the user and all their articles?"},class: "btn btn-danger btn-md" %>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 align="center">SignUp for Alpha Blog</h2>

<%= render 'form'%>

app/views/users/show.html.erb
<h2 align="center">Welcome to <%= @user.username %>'s page</h2>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username%>'s articles</h4>

<div class="center">
  <%= will_paginate @user_articles%>
  <%= render 'articles/articles' , obj: @user_articles  %>
  <%= will_paginate @user_articles%>
</div>